### ISSUE TITLE
Multi-modal text and audio

### ISSUE THREAD

**Issue by jbmaxwell** [kyegomez/MultiModalMamba#7]
First, thanks for this repo! 

I'd like to run some tests on generating audio from text and text descriptions from audio. I'll be using encoded audio latents for input/output, so the input shape would change but will be comparable in size to your `(3, 224, 224)` image example. I'm just a bit confused by the output shapes from the `model_example.py` script, which appear to return the text embeddings only `(1, 196, 10000)`, whereas I'd like to get both the text and the image (audio latent, in my case). If I set `return_embeddings = True` I get the embeddings, as expected, but I'm not seeing any image-like shapes.

Any guidance to offer?

**Comment by kyegomez** [comment]
@jbmaxwell Hey so the model will output a text description of the image, it won't output an image. For this you should look into next gpt, unified io 2, and gemini. I'm actively learning about this as well so I advise you to join Agora and keep in touch!

https://discord.gg/

**Comment by jbmaxwell** [comment]
@kyegomez Thanks for the speedy reply! 
So are these also based on Mamba, or are they all Transformers? I'm mostly curious about application of SSMs in the audio space.

**Comment by kyegomez** [comment]
@jbmaxwell yes this is based on mamba, and we haven't seen ssms in audio, that would be an interesting idea. What would be the objective, understand audio or speech or generate speech?

SSMs in audio would be novel.

**Comment by jbmaxwell** [comment]
My particular application would be conditional music generation (e.g., text-to-music), to improve the LLM performance of transformer-based models like MusicLM (Google) and MusicGen (Meta). But also music-to-text, for data augmentation (i.e., generate text descriptions from unlabelled/annotated audio, to expand paired music/text training sets).

**Comment by kyegomez** [comment]
@jbmaxwell just added this feature in to process audio! If you could find a way to also add it to the fusion logic that would be massive!

**Comment by jbmaxwell** [comment]
@kyegomez I can certainly have a look and let you know. I see you've added a function from `zeta` to handle audio input, so I'll see what I can do with that. 

One distinction here, mind you, is that I'll be working with audio latents from a pretrained VAE. This is pretty typical in generative music (e.g., in MusicLM, MusicGen, Stable Audio), where neural audio codecs and/or VAEs are used to compress the raw audio *before* it hits the LM or Diffusion model (since the raw audio (wav/pcm) representations are just very large). 

Even though part of the point of Mamba is handling very long sequences, I think it makes sense to compress the audio as a preprocessing step. A typical input shape in a music model (e.g., Stable Audio) is `(bs, 32, 2048)`, which will encode around 48 seconds of 44.1khz stereo audio. That's partly why I thought to just give your image version a shot, then start hacking (haha)—because the compressed audio sizes are comparable to image sizes.  

However, since Mamba does handle very long sequences, we could also assume a much shorter sequence as input—e.g, instead of `(bs, 32, 2048)` we could do something like `(bs, 32, 128)` so that Mamba is working with 1s chunks of audio... or we could just flatten it down to `(bs, 32, 1)` (i.e., `(bs, 32)`)... Not sure what's best. We certainly could also skip the compression, but that would probably be more of a theoretical approach than the kind of thing folks in the audio generation space will use (i.e., they'll probably want a version that works with compressed representations anyway).

We could also just specify it separately as a multi-purpose "latent" input (e.g., "Latent Mamba")... ?

Just my 2¢.
